routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   if(!auth()->user()){
      return redirect()->route('login');
   }else{
      return redirect()->route('blog');
   }
});
// Route::get('/portal', function () {
//     return view('content');
// });
//Route::get('/', 'Web\ContentController@welcome')->name('welcome');
//Route::get('/', 'Web\ContentController@welcome')->name('welcome');
//Route::get('/portal', 'Web\ContentController@blog1');
//Route::get('/articulo/{slug}', 'Web\ContentController@post')->name('post');
//Route::get('/subcategory/{slug}', 'Web\ContentController@subcategory')->name('subcategory');
Auth::routes();
//ROUTES ADMIN
Route::get('/dashboard/blogs', 'Admin\PageController@blog')->name('blog');
Route::get('/post/{slug}', 'Admin\PageController@post')->name('post');
Route::get('/subcategory/{slug}', 'Admin\PageController@subcategory')->name('subcategory');
//Route::get('/tag/{slug}', 'Admin\PageController@tag')->name('tag');

//ROUTES ADMIN
//Route::resource('tags', 		'Admin\TagController');
Route::resource('categories', 	'Admin\CategoryController');
Route::resource('subcategories', 	'Admin\SubcategoryController');
Route::resource('posts', 		'Admin\PostController');
//Route::get('/subcategory/{id}', 'Web\PageController@getSubcategory')->name('apiCategory');

//Rutas de la parte del perfil
Route::group(["middleware" => ['auth', 'verified'], "as" => "profile."], function(){
   Route::get('profile', 'Admin\ProfileController@index')->name('index');
   Route::put('profile/{user}/update', 'Admin\ProfileController@update')->name('put');
   Route::put('profile/change_password', 'Admin\ProfileController@change_password')->name('change_password');
   Route::get('profile/posts', 'Admin\ProfileController@get_posts')->name('posts');
});

Route::group(["middleware" => ['auth', 'verified'], "as" => "admin."], function(){
   Route::get('admin/users', 'Admin\AdminController@index')->name('index');
   Route::get('admin/users/get', 'Admin\AdminController@get')->name('get');
   Route::put('admin/update', 'Admin\AdminController@update')->name('put');
   Route::get('admin/posts/', 'Admin\AdminController@posts')->name('posts');
   Route::delete('admin/{user}/destroy', 'Admin\AdminController@destroy')->name('destroy');
   Route::put('admin/{user}/change_status', 'Admin\AdminController@change_status')->name('change_status');
   Route::post('admin/post/comment', 'Admin\AdminController@comment')->name('comment');
   Route::put('admin/{post}/acept', 'Admin\AdminController@aceptPost')->name('acept_post');
});

Route::group(["middleware" => ['auth', 'verified'], "as" => "banners."], function(){
   Route::get("banners", "Admin\BannerController@index")->name("index");
   Route::post("banners", "Admin\BannerController@store")->name("store");
   Route::get("banners/get", "Admin\BannerController@get")->name("get");
   Route::delete("banners/{id}/destroy", "Admin\BannerController@destroy")->name('destroy');
});


Route::group(["middleware" => ["auth", 'verified'], "as" => "logos."], function(){
   Route::get("logos", "Admin\LogoController@index")->name('index');
   Route::post("logos", "Admin\LogoController@store")->name('store');
   Route::get("logos/get", "Admin\LogoController@get")->name('get');
   Route::delete("logos/{id}/destroy", "Admin\LogoController@destroy")->name('destroy');
});


Route::put('posts/{id}/send_review', 'Admin\PostController@send_review')->name('post.send_review');

Route::group(["middleware" => ["auth", "verified"], "as" => "fondo3."], function(){
   Route::get('fondo-iii', 'Admin\Fondo3Controller@index')->name('index');
   Route::get('fondo-iii/getUsers', 'Admin\Fondo3Controller@getUsers')->name('getUsers');
   Route::get('fondo-iii/{id}/history', 'Admin\Fondo3Controller@history')->name('history');
   Route::get('fondo-iii/{id}/getCfdis', 'Admin\Fondo3Controller@getCFDIs')->name('cfdis');
   Route::post('fondo-iii/uploadCFDIsUA', 'Admin\Fondo3Controller@uploadCFDIsUA')->name('uploadCFDIsUA');
   Route::put('fondo-iii/{id}/aprobar-cfdi', 'Admin\Fondo3Controller@aprobarCFDI')->name('aprobarCFDI');
   Route::put('fondo-iii/rechazar-cfdi', 'Admin\Fondo3Controller@rechazarCFDI')->name('rechazarCFDI');
   Route::get('fondo-iii/{id}/verCFDI', 'Admin\Fondo3Controller@verCFDI')->name('verCFDI');
   Route::put('fondo-iii/{id}/uploadCFDIsUM', 'Admin\Fondo3Controller@uploadCFDIsUM')->name('uploadCFDIsUM');
});

Route::group(["middleware" => ["auth", "verified"], "as" => "fondo4."], function(){
   Route::get('fondo-iv', 'Admin\Fondo4Controller@index')->name('index');
   Route::get('fondo-iv/getUsers', 'Admin\Fondo4Controller@getUsers')->name('getUsers');
   Route::get('fondo-iv/{id}/history', 'Admin\Fondo4Controller@history')->name('history');
   Route::get('fondo-iv/{id}/getCfdis', 'Admin\Fondo4Controller@getCFDIs')->name('cfdis');
   Route::post('fondo-iv/uploadCFDIsUA', 'Admin\Fondo4Controller@uploadCFDIsUA')->name('uploadCFDIsUA');
   Route::put('fondo-iv/{id}/aprobar-cfdi', 'Admin\Fondo4Controller@aprobarCFDI')->name('aprobarCFDI');
   Route::put('fondo-iv/rechazar-cfdi', 'Admin\Fondo4Controller@rechazarCFDI')->name('rechazarCFDI');
   Route::get('fondo-iv/{id}/verCFDI', 'Admin\Fondo4Controller@verCFDI')->name('verCFDI');
   Route::put('fondo-iv/{id}/uploadCFDIsUM', 'Admin\Fondo4Controller@uploadCFDIsUM')->name('uploadCFDIsUM');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'user_id', 'subcategory_id', 'name', 'slug', 'excerpt', 'body', 'status', 'file'
    ];

    public function subcategory()
    {
        return $this->belongsTo(Subcategories::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\PostStoreRequest;
use App\Http\Requests\PostUpdateRequest;

use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Storage;

use App\Post;
use App\Category;
use App\Subcategories;

use Illuminate\Contracts\Events\Dispatcher;
use App\Http\Controllers\MenuFilterController;


class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('verified');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);

        $posts = Post::orderBy('id', 'DESC')
            ->where('user_id', auth()->user()->id)
            ->paginate();

        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Dispatcher $events)
    {
        //$categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');
        $menu = new MenuFilterController();
        $menu->menuFilter($events);

        $subcategories= Subcategories::orderBy('name', 'ASC')->pluck('name', 'id');

        return view('admin.posts.create', compact('subcategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostStoreRequest $request)
    {
        $post = Post::create($request->all());
        //$this->authorize('pass', $post);

        //IMAGE 
        if($request->file('image')){
            $path = Storage::disk('public')->put('image',  $request->file('image'));
            $post->fill(['file' => asset($path)])->save();
        }
        //TAGS
       // $post->subcategories()->attach($request->get('subcategories'));

        return redirect()->route('post', $post->slug);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);

        $post = Post::find($id);
        //$this->authorize('pass', $post);

        return view('admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);
        

        //$categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');
        $subcategories= Subcategories::orderBy('name', 'ASC')->pluck('name', 'id');
        $post= Post::find($id);
        if($post == null || $post->user_id != auth()->user()->id){
            abort(404);
        }else{
            return view('admin.posts.edit', compact('post','subcategories'));
        }
       // $this->authorize('pass', $post);

        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, $id)
    {
        $post = Post::find($id);
        //$this->authorize('pass', $post);

        $post->status = "DRAFT";
        $post->validated = 0;

        $post->fill($request->all())->save();

        //IMAGE 
        if($request->file('image')){
            $path = Storage::disk('public')->put('image',  $request->file('image'));
            $post->fill(['file' => asset($path)])->save();
        }

        //TAGS
       // $post->categories()->sync($request->get('categories'));

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id)->delete();
        //$this->authorize('pass', $post);

        return back()->with('eliminar','ok');
    }

    //Funcion de envio a revision de post.
    public function send_review($id)
    {
        $post = Post::find($id);
        $post->validated = 1;
        $post->save();
        alert()->success('Éxito', 'Post enviado a revisión.');
        return redirect()->back();
    }
}

resources/views/posts/index.blade.php
@extends('adminlte::page')

@section('title', 'Artículos en revisión.')

@section('content_header')
    <h1>Artículos en revisión</h1>
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Lista de artículos por aceptar.
                </div>

                <div class="card-body">

                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Subcategoria Perteneciente</th>
                                <th colspan="3">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($posts as $post)
                            <tr>
                            
                                <td>{{ $post->name }}</td>
                                <td>{{$post->subcategory_id}}</td>
                                <td width="10px">
                                    <a href="{{ route('post', $post->slug) }}" class="btn btn-sm btn-default">Ver</a>
                                </td>
                                <td width="10px">
                                    {!! Form::open(['class'=>'put','route' => ['admin.acept_post', $post->id], 'method' => 'PUT']) !!}
                                        <button class="btn btn-sm btn-success">
                                            <i class="far fa-check-circle"></i>
                                        </button> 
                                    {!! Form::close() !!}
                                </td>
								<td width="10px">
									<button class="refuse btn btn-sm btn-danger" value="{{$post->id}}">
										<i class="fas fa-times"></i>
									</button> 
								</td>
                            </tr>
                            @endforeach
                        </tbody>   
                    </table>     	
                </div>
            </div>
        </div>
    </div>
</div>

{{--Modal para los comentarios--}}
<div class="modal fade" id="add_comment" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Añadir comenarios.</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('admin.comment')}}" method="POST">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label>Comentario:</label>
                        <textarea class="form-control" rows="3" name="comment" placeholder="Escribe aquí tu comentario..."></textarea>
                        <input type="hidden" id="post_id" name="post_id">
                    </div>
                    @if ($errors->has('comment'))
						<span>
							<strong style="color:red">{{$errors->first('comment')}}</strong>
						</span>
                    @endif
					<br>
					<button type="submit" class="btn btn-primary btn-lg">Enviar comentarios.</button>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@include('sweetalert::alert')
    <script>
		$(document).ready(function(){
			$(document).on('click', '.refuse', function(){
				$('#post_id').val($(this).val());
				$('#add_comment').modal('show');
			});
		});
	</script>
@stop