routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   if(!auth()->user()){
      return redirect()->route('login');
   }else{
      return redirect()->route('blog');
   }
});
// Route::get('/portal', function () {
//     return view('content');
// });
//Route::get('/', 'Web\ContentController@welcome')->name('welcome');
//Route::get('/', 'Web\ContentController@welcome')->name('welcome');
//Route::get('/portal', 'Web\ContentController@blog1');
//Route::get('/articulo/{slug}', 'Web\ContentController@post')->name('post');
//Route::get('/subcategory/{slug}', 'Web\ContentController@subcategory')->name('subcategory');
Auth::routes();
//ROUTES ADMIN
Route::get('/dashboard/blogs', 'Admin\PageController@blog')->name('blog');
Route::get('/post/{slug}', 'Admin\PageController@post')->name('post');
Route::get('/subcategory/{slug}', 'Admin\PageController@subcategory')->name('subcategory');
//Route::get('/tag/{slug}', 'Admin\PageController@tag')->name('tag');

//ROUTES ADMIN
//Route::resource('tags', 		'Admin\TagController');
Route::resource('categories', 	'Admin\CategoryController');
Route::resource('subcategories', 	'Admin\SubcategoryController');
Route::resource('posts', 		'Admin\PostController');
//Route::get('/subcategory/{id}', 'Web\PageController@getSubcategory')->name('apiCategory');

//Rutas de la parte del perfil
Route::group(["middleware" => ['auth', 'verified'], "as" => "profile."], function(){
   Route::get('profile', 'Admin\ProfileController@index')->name('index');
   Route::put('profile/{user}/update', 'Admin\ProfileController@update')->name('put');
   Route::put('profile/change_password', 'Admin\ProfileController@change_password')->name('change_password');
   Route::get('profile/posts', 'Admin\ProfileController@get_posts')->name('posts');
});

Route::group(["middleware" => ['auth', 'verified'], "as" => "admin."], function(){
   Route::get('admin/users', 'Admin\AdminController@index')->name('index');
   Route::get('admin/users/get', 'Admin\AdminController@get')->name('get');
   Route::put('admin/update', 'Admin\AdminController@update')->name('put');
   Route::get('admin/posts/', 'Admin\AdminController@posts')->name('posts');
   Route::delete('admin/{user}/destroy', 'Admin\AdminController@destroy')->name('destroy');
   Route::put('admin/{user}/change_status', 'Admin\AdminController@change_status')->name('change_status');
   Route::post('admin/post/comment', 'Admin\AdminController@comment')->name('comment');
   Route::put('admin/{post}/acept', 'Admin\AdminController@aceptPost')->name('acept_post');
});

Route::group(["middleware" => ['auth', 'verified'], "as" => "banners."], function(){
   Route::get("banners", "Admin\BannerController@index")->name("index");
   Route::post("banners", "Admin\BannerController@store")->name("store");
   Route::get("banners/get", "Admin\BannerController@get")->name("get");
   Route::delete("banners/{id}/destroy", "Admin\BannerController@destroy")->name('destroy');
});


Route::group(["middleware" => ["auth", 'verified'], "as" => "logos."], function(){
   Route::get("logos", "Admin\LogoController@index")->name('index');
   Route::post("logos", "Admin\LogoController@store")->name('store');
   Route::get("logos/get", "Admin\LogoController@get")->name('get');
   Route::delete("logos/{id}/destroy", "Admin\LogoController@destroy")->name('destroy');
});


Route::put('posts/{id}/send_review', 'Admin\PostController@send_review')->name('post.send_review');

Route::group(["middleware" => ["auth", "verified"], "as" => "fondo3."], function(){
   Route::get('fondo-iii', 'Admin\Fondo3Controller@index')->name('index');
   Route::get('fondo-iii/getUsers', 'Admin\Fondo3Controller@getUsers')->name('getUsers');
   Route::get('fondo-iii/{id}/history', 'Admin\Fondo3Controller@history')->name('history');
   Route::get('fondo-iii/{id}/getCfdis', 'Admin\Fondo3Controller@getCFDIs')->name('cfdis');
   Route::post('fondo-iii/uploadCFDIsUA', 'Admin\Fondo3Controller@uploadCFDIsUA')->name('uploadCFDIsUA');
   Route::put('fondo-iii/{id}/aprobar-cfdi', 'Admin\Fondo3Controller@aprobarCFDI')->name('aprobarCFDI');
   Route::put('fondo-iii/rechazar-cfdi', 'Admin\Fondo3Controller@rechazarCFDI')->name('rechazarCFDI');
   Route::get('fondo-iii/{id}/verCFDI', 'Admin\Fondo3Controller@verCFDI')->name('verCFDI');
   Route::put('fondo-iii/{id}/uploadCFDIsUM', 'Admin\Fondo3Controller@uploadCFDIsUM')->name('uploadCFDIsUM');
});

Route::group(["middleware" => ["auth", "verified"], "as" => "fondo4."], function(){
   Route::get('fondo-iv', 'Admin\Fondo4Controller@index')->name('index');
   Route::get('fondo-iv/getUsers', 'Admin\Fondo4Controller@getUsers')->name('getUsers');
   Route::get('fondo-iv/{id}/history', 'Admin\Fondo4Controller@history')->name('history');
   Route::get('fondo-iv/{id}/getCfdis', 'Admin\Fondo4Controller@getCFDIs')->name('cfdis');
   Route::post('fondo-iv/uploadCFDIsUA', 'Admin\Fondo4Controller@uploadCFDIsUA')->name('uploadCFDIsUA');
   Route::put('fondo-iv/{id}/aprobar-cfdi', 'Admin\Fondo4Controller@aprobarCFDI')->name('aprobarCFDI');
   Route::put('fondo-iv/rechazar-cfdi', 'Admin\Fondo4Controller@rechazarCFDI')->name('rechazarCFDI');
   Route::get('fondo-iv/{id}/verCFDI', 'Admin\Fondo4Controller@verCFDI')->name('verCFDI');
   Route::put('fondo-iv/{id}/uploadCFDIsUM', 'Admin\Fondo4Controller@uploadCFDIsUM')->name('uploadCFDIsUM');
});

app/Fondo4.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fondo4 extends Model
{
    protected $fillable = [
        'id', 'user_id', 'm_user_id', 'file', 'file_user',
    ];
}

app/Http/Controllers/Admin/Fondo4Controller.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use Yajra\DataTables\DataTables;

use Illuminate\Contracts\Events\Dispatcher;
use App\Http\Controllers\MenuFilterController;

use App\User;
use App\Fondo4;
use App\Fondo4Comments;

use App\Notifications\NewFondoPdfNotification;
use App\Notifications\FondoCFDIUpdateNotification;
use App\Notifications\AprobarCFDINotification;
use App\Notifications\RechazarCFDINotification;

use App\Http\Requests\Fondo3\StoreUserFile;
use App\Http\Requests\Fondo3\StoreUserMFile;
 
use Jenssegers\Date\Date;

class Fondo4Controller extends Controller
{
    public function index(Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);

        if(auth()->user()->role == "ADMINISTRADOR"){
            return view('admin.municipios.fondo4.admin.index');
        }else if(auth()->user()->role == "MUNICIPIO"){
            return view('admin.municipios.fondo4.index');
        }else{
            abort(403);
        }
    }

    public function getUsers()
    {
        return DataTables::of(User::get()->where('role', 'MUNICIPIO'))
        ->addColumn('view', 'admin.municipios.fondo4.admin.view')
        ->addColumn('role_user', 'admin.users.role')
        ->rawColumns(['view', 'role_user'])
        ->toJson();
    }

    public function history($id, Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);
        $user = User::find($id);

        if(auth()->user()->role == "ADMINISTRADOR" && $user->role == "MUNICIPIO"){
            return view('admin.municipios.fondo4.admin.profile', [
                'user' => $user,
            ]);
        }
        abort(403);
    }

    public function getCFDIs($id)
    {
        return DataTables::of(Fondo4::get()->where('m_user_id', $id))
        ->addColumn('estado', 'admin.municipios.estado')
        ->addColumn('view_pdf', 'admin.municipios.view_pdf')
        ->addColumn('view_pdf_m', 'admin.municipios.view_pdf_m')
        ->addColumn('aceptar', 'admin.municipios.fondo4.admin.aceptar')
        ->addColumn('rechazar', 'admin.municipios.rechazar')
        ->addColumn('view_all', 'admin.municipios.fondo4.view_all')
        ->rawColumns(['estado', 'aceptar', 'rechazar', 'view_pdf', 'view_pdf_m', 'view_all'])
        ->toJson();
    }

    public function uploadCFDIsUA(StoreUserFile $request)
    {
        $anio = date('Y');

        $fondo4 = (new Fondo4)->fill($request->all());
        $fondo4->file_user = $request->file('file_user')->store('public/pdfs/finanzas/fondo4/' . $anio);
        $fondo4->user_id = auth()->user()->id;
        $fondo4->anio = $anio;
        $fondo4->month = ucwords(Date::now()->format('F'));
        $fondo4->save();

        //Metodo para enviar el correo electronico al municipio.
        $user = User::find($request->m_user_id);
        $user->notify(new NewFondoPdfNotification(4));

        alert()->success('Exito!', 'El pdf ha sido guardado con éxito.');
        return redirect()->back();
    }

    public function aprobarCFDI($id)
    {
        $fondo4 = Fondo4::find($id);
        $fondo4->status = "APROBADO";

        $user = User::find($fondo4->m_user_id);
        $user->notify(new AprobarCFDINotification(4, $id));

        $fondo4->save();
        alert()->success('Exito!', 'El CFDI ha sido aprobado.');
        return redirect()->back();
    }

    public function rechazarCFDI(Request $request)
    {
        $fondo4 = Fondo4::find($request->fondo4_id);
        $fondo4->status = "RECHAZADO";
        //Se quedara pendiente ya que aun no existen los archivos por parte de los municipios
        Storage::delete($fondo4->file);
        $fondo4->file = "EN ESPERA...";
        $fondo4->save();
        
        $comment = (new Fondo4Comments)->fill($request->all());
        $comment->user_id = auth()->user()->id;
        $comment->save();

        $user = User::find($fondo4->m_user_id);
        $user->notify(new RechazarCFDINotification(4, $fondo4->id, $request->comment));

        alert()->success('Exito!', 'El comentario ha sido guardado.');
        return redirect()->back();
    }

    public function verCFDI($id, Dispatcher $events)
    {
        $menu = new MenuFilterController();
        $menu->menuFilter($events);
        
        $fondo4 = Fondo4::find($id);
        $comments = Fondo4Comments::where('fondo4_id', $fondo4->id)
        ->join('users', 'users.id', 'fondo4_comments.user_id')
        ->select('fondo4_comments.*', 'users.name')
        ->get();
        return view('admin.municipios.fondo4.show', [
            'fondo4' => $fondo4,
            'comments' => $comments,
        ]);
    }

    public function uploadCFDIsUM($id, StoreUserMFile $request)
    {
        $anio = date('Y');

        $fondo4 = Fondo4::find($id);
        $fondo4->file = $request->file('file')->store('public/pdfs/municipio/fondo4/' . $anio);
        $fondo4->status = "EN REVISION";
        $fondo4->save();
        //Espacio para el envio de notificaciones.
        $user = User::find($fondo4->user_id);
        $municipio = User::find($fondo4->m_user_id);
        $user->notify(new FondoCFDIUpdateNotification(4, $municipio->name, $municipio->id));

        alert()->success('Exito!', 'El CFDI ha sido guardado y enviado a revisión con éxito.');
        return redirect()->back();
    }
}

resources/views/admin/municipios/fondo4/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Fondo 4.</h1>
@stop

@section('content')
<div class="container">
	<div class="row">
			<div class="col-lg-12">
				<div class="table-responsive">
					<table id="fondo3" style="text-align:center;" class="table table-striped table-bordered" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Archivo.</th>
							<th>Mes.</th>
							<th>Año.</th>
							<th>Estatus.</th>
						</tr>
					</thead>
					<tbody></tbody>
				   </table>
				</div>
			</div>
	</div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

	<!-- jQuery, Popper.js, Bootstrap JS -->
	<script src="{{ asset('assets/js/jquery-3.4.1.min.js') }}"></script>
	<script src="{{ asset('assets/js/popper.min.js') }}"></script>
	<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>

	<!-- datatables JS -->
	<script src="{{ asset('assets/js/datatables.min.js') }}"></script>

	@include('sweetalert::alert')
    <script>
        $(document).ready(function(){
            fondo3();
            function fondo3()
            {
                $('#fondo3').DataTable({
                    language: {
						url: "http://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json",
					},
					ajax: {
						method: "GET",
						url: "{{route('fondo4.cfdis', auth()->user()->id)}}",
					},
					columns: [
						{data: "view_all"},
                        {data: "month"},
                        {data: "anio"},
                        {data: "estado"},
					]
                });
            }
        });
    </script>
@stop

resources/views/admin/municipios/fondo4/show.blade.php
@extends('adminlte::page')

@section('title', 'Fondo 4. Detalles.')

@section('content_header')
    <h1>Fondo 4. / {{$fondo4->anio}} / {{$fondo4->month}}</h1>
@stop

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <h3 class="profile-username text-center"></h3>
                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Estado: </b> <a class="float-right">
                                    @if ($fondo4->status == "PENDIENTE")
                                        <small class="badge badge-warning"><i class="fas fa-hourglass-end"></i> PENDIENTE</small>
                                    @elseif ($fondo4->status == "EN REVISION")
                                        <small class="badge badge-info"><i class="far fa-clock"></i> EN REVISION</small>
                                    @elseif ($fondo4->status == "RECHAZADO")
                                        <small class="badge badge-danger"><i class="fas fa-times"></i> RECHAZADO</small>
                                    @else
                                        <small class="badge badge-success"><i class="far fa-thumbs-up"></i> APROBADO</small>
                                    @endif
                                </a>
                            </li>
                            <li class="list-group-item">
                                <b>Fecha de subida: </b><a class="float-right" style="color:green">{{$fondo4->created_at->diffForHumans()}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Ultima modificación: </b><a class="float-right" style="color:green">{{$fondo4->updated_at->diffForHumans()}}</a>
                            </li>
                            @if ($fondo4->file == "EN ESPERA...")
                            <li class="list-group-item">
                                <b>Mensaje del sistema: </b> <a class="float-right"><small class="badge badge-warning"><i class="fas fa-hourglass-end"></i> POR FAVOR SUBE TU CFDI.</small></a>
                            </li>
                            <br>
                            <a href="#" class="cfdi btn btn-secondary btn-block"><b>Subir CFDI.</b></a>
                            @endif
                        </ul>
                    </div>
                    <div class="card-footer">
                        <ul class="list-group list-group-unbordered mb-3">
                            <b>Comentarios:</b>
                            @if (!$comments->count())
                                <li class="list-group-item">
                                    <b>Usuario: </b>El equipo de ChecaTuLana.
                                    <br>
                                    <b>Mensaje: </b>Aun no existen comentarios para este CFDI, favor de esperar un poco más.
                                </li>
                            @else
                                @foreach ($comments as $comment)
                                    <li class="list-group-item">
                                        <b>Usuario: </b> {{$comment->name}}
                                        <br>
                                        <b>Mensaje: </b>{{$comment->comment}}
                                    </li>
                                @endforeach
                            @endif
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <h2>Comprobante de pago.</h2>
                        <br>
                        <p align="center">
                            <iframe src="{{Storage::url($fondo4->file_user)}}#toolbar=0" width="90%" height="600px">
                            </iframe>
                        </p>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a download="Fondo4_{{$fondo4->anio}}_{{$fondo4->month}}" href="{{Storage::url($fondo4->file_user)}}" class="btn btn-secondary btn-block"><b>Descargar PDF.</b></a>
                    </div>
                </div>
                <!-- /.card -->
                @if ($fondo4->file == "EN ESPERA...")
                {{--No se muestra nada ya que no existe el pdf en el sistema--}}
                @else
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <h2>Vista previa de mi CFDI.</h2>
                            <br>
                            <p align="center">
                                <iframe src="{{Storage::url($fondo4->file)}}#toolbar=0" width="90%" height="600px">
                                </iframe>
                            </p>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                        </div>
                    </div>
                @endif
                
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>

<div class="modal fade" id="upload_file" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
       <div class="modal-content">
          <div class="modal-header">
             <h4 class="modal-title">Subir nuevo pdf.</h4>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
             <span aria-hidden="true">×</span>
             </button>
         </div>
        <div class="modal-body">
            <form action="{{ route('fondo4.uploadCFDIsUM', $fondo4->id) }}" method="POST" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="input-group">
                    <input type="file" name="file" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
                    <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Subir</button>
                </div>
                @if ($errors->has('file'))
                    <span>
                        <strong style="color:red">{{$errors->first('file')}}</strong>
                    </span>
                @endif
                <br>
            </form>
        </div>
       </div>
       <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    @include('sweetalert::alert')

    <script>
        $(document).ready(function(){
            $(document).on('click', '.cfdi', function(){
                $("#upload_file").modal('show');
            });
        });
    </script>
@stop

resources/views/admin/municipios/fondo4/view_all.blade.php
<a href="{{route('fondo4.verCFDI', $id)}}" class="btn btn-sm btn-default">Ver archivo.</a>